name: Required Check for PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Do nothing
        run: echo "This is a placeholder job that does nothing."
